# Generated by Django 4.2 on 2023-07-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_created',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='date_updated',
            new_name='update_date',
        ),
    ]
