# Generated by Django 4.2 on 2023-07-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('Management', 'Gestion'), ('SUPPORT', 'Support'), ('Sale', 'Vente')], max_length=40),
        ),
    ]
