# Generated by Django 4.2 on 2023-07-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_delete_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'Gestion'), ('SUPPORT', 'Support'), ('COMMERCIAL', 'Vente')], max_length=40),
        ),
    ]
