# Generated by Django 4.2 on 2023-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGEMENT', 'Gestion'), ('SUPPORT', 'Support'), ('COMMERCIAL', 'Vente')], max_length=20),
        ),
    ]
